#设置端口
server:
  port: 80

#数据源配置（阿里云数据库）
spring:
  datasource:
      url: jdbc:mysql://47.96.114.71:3306/blog?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: pengbowen
      driver-class-name: com.mysql.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource
#thymeleaf配置
  thymeleaf:
    mode: html5
    encoding: utf-8
    cache: false
#静态资源

#日志配置
logging:
  #配置日志文件路径
  file: log\cms.log
  level:
    root: info
    com.zzsh.cms:info
#mybatis配置
mybatis:
  type-aliases-package: com.zzsh.cms.pojo
  mapper-locations: classpath:mapper/*.xml


